### ISSUE TITLE
1.18.2 port

### ISSUE THREAD

**Issue by Multex** [antoninvf/fabricMaxwellPlaceableCat#1]
So, I'm making a server with some friends and we would like to use the mod but it's not for 1.18.2. I wanted to ask if you plan to make a port for that version

**Comment by flowyan** [comment]
I was actually planning on abandoning Fabric all together and moving to Forge as it's better for actual content mods. On Fabric the part that actually loads the model of maxwell doesn't work with some other Fabric mods like Create Fabric.
